name: Build and Test Frontend
on: 
  pull_request:
    branches: [ master, develop ]
  workflow_dispatch:

defaults:
  run:
    working-directory: Frontend

jobs:
  build:
    name: Install dependencies, test and build frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x] #Run on all node-versions of 14.x and 15.x

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Run yarn commands
      run: |
        yarn install
        yarn build
        yarn test