name: frontend_linting

on:
  push:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    working-directory: Frontend
    
jobs:
  build:
    name: Lint frontend
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Install modules
      run: yarn install
    - name: Run ESLint
      run: yarn run eslint . --ext .js,.jsx,.ts,.tsx
